version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "timeout-exceeded-alarm-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-18q77yg1aiyo6"
s3_prefix = "timeout-exceeded-alarm-test"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Timeout=\"25\""
